### ISSUE TITLE
Behaviour

### ISSUE THREAD

**Issue by farukjr** [AmbeGod/Customer-registration#6]
Good work guys..
After testing the second version, i discovered that the name field needs to be validated to take only alphabets and not numbers or any other character, also the date of birth field should be updated to make it more user friendly....

**Comment by AmbeGod** [comment]
ok @farukjr that is a good discovery, lets work on it for the 3rd version

**Comment by jummydotcom** [comment]
yes that would be a nice feature and it would also be User friendly

**Comment by farukjr** [comment]
actually I am working on it, I should upload it before the day runs out...

**Comment by farukjr** [comment]
@AmbeGod  & @jummydotcom 
I added the codes already

**Comment by AmbeGod** [comment]
Weldon guys
